absolute_urls: false

home:
  alias: '/home'

pages:
  theme: zemwiki
  markdown_extra: false
  process:
    markdown: true
    twig: true

languages:
  http_accept_language: true
  session_store_active: true
  supported:
    - de
    - fr

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
